### ISSUE TITLE
controler tracking behaving wierd.

### ISSUE THREAD

**Issue by blenderman94** [bjornbytes/lovr#817] opened 2024-12-07 13:03 UTC
Hello  again. im running lovr on a quest 2 and  for some reason controler tracking  not work at all but hand tracking do work. what is not even supported so far as i know :D  (its not tracking on android , but  when i use pc vr it works) im on the lastest update on quest2 .
the problem i need to run my app on a headset standalone so its a bit strange situation.
thx in advance.

**Comment by blenderman94** [comment] 2024-12-07 14:03
i update to the latest  experimental build what looks like okay so far

**Comment by bjornbytes** [comment] 2024-12-07 18:39
This is probably a duplicate of #783, there are some weird issues with Quest controllers that we've been trying to figure out.  But, does your second comment mean it was fixed once you updated?

**Closed as not planned** 2024-12-07 22:46 UTC

**Comment by Olivfhan** [comment] 2024-12-09 20:31
I was running into similar issues as blenderman's, hand tracking worked fine but controllers were being ignored when using the quest 2. I'm assuming their issue got fixed when updating to the latest nightly because mine have as well; using the debugging snippet from the lövr page seems to show that hand tracking may not be working completely on the nightly (only tracking position now, not gestures), but controllers are fixed
