### ISSUE TITLE
Arc/circle texture coordinates

### ISSUE THREAD

**Issue by monolifed** [bjornbytes/lovr#495] opened 2021-10-09 10:38 UTC
Are the texture coordinates of lovr.graphics.arc and lovr.graphics.circle correct?
They are between -0.5 and 1.5 (instead of what I expected: 0-1)

**Comment by bjornbytes** [comment] 2021-10-09 10:46
It's not the intended behavior.  Seems this was a regression from 429efcb38d820bc63ce7668f40bad7b8006a371a.

**Comment by bjornbytes** [comment] 2021-10-09 10:54
This should be fixed now in 0a2f9688500c6f228dd5b5a86a9cb796aff302c0

**Closed as completed by bjornbytes** 2021-10-09 10:54 UTC
Labels: bug
