### ISSUE TITLE
NAN if dt is high in headset_simulator

### ISSUE THREAD

**Issue by nensanders** [bjornbytes/lovr#760] opened 2024-03-17 13:32 UTC
https://github.com/bjornbytes/lovr/blob/26d17fc4029d12a641e575cd713b3f18d7b96170/src/modules/headset/headset_simulator.c#L468

When restarting on a simulated headset platform the dt can become so high that this line produces a NAN, which breaks rendering further down the line.

I would suggest clamping it at the start of the function.

**Comment by bjornbytes** [comment] 2024-03-17 21:03
Ah, I had already fixed this in https://github.com/bjornbytes/lovr/pull/727, but it hasn't been merged yet.  This was actually caused by a *negative* dt resulting from forgetting to reset the timing variables properly.  I applied the fix to the stable/dev branches.  Thanks!

**Closed as completed by bjornbytes** 2024-03-17 21:03 UTC
Labels: bug
